import Head from "next/head";
import { Inter } from "next/font/google";
import Layout from "@/layout/Layout";
import GeneralContact from "@/components/Forms/Contact/GeneralContact";

const inter = Inter({ subsets: ["latin"] });

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact Nine Virtual Technologies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${inter.className}`}>
        <Layout>
          <div id="contact" className="header-padding-top">
            <div className="contact-header">
              <h1>Get in Touch</h1>
              <p>
                {`We're here to help you with all your cloud service needs. Whether
              you have questions, need assistance, or want to discuss how our
              cloud solutions can benefit your business, we're just a message
              away.`}
              </p>

              <p>
                {`Please fill out the form below, and we'll get back to you as
              soon as possible. Your satisfaction is our top priority, and we
              look forward to assisting you on your cloud journey.`}
              </p>
            </div>

            <GeneralContact />
          </div>
        </Layout>
      </main>
    </>
  );
}
